//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetTask.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ID { get; set; }
        public int DayID { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public int CourseID { get; set; }
        public int RoomID { get; set; }
        public int TrainerID { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Day Day { get; set; }
        public virtual Room Room { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
